# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-31 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ForumAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ForumAccount.UserProfile'),
        ),
    ]
