# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-01 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ForumAccount', '0002_auto_20200331_1326'),
    ]                    
    # 0002_auto_20200331_1326
    #                         0002_auto_20200401_2049

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_value', models.IntegerField(default=0)),
                ('likes_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ForumAccount.UserProfile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ForumAccount.Post')),
            ],
        ),
    ]
