# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-06 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumAccount', '0004_post_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='likes_list',
        ),
        migrations.AddField(
            model_name='likes',
            name='likes_list',
            field=models.ManyToManyField(null=True, to='ForumAccount.UserProfile'),
        ),
    ]
