# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-08 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumAccount', '0006_auto_20200408_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='likes_list',
            field=models.ManyToManyField(blank=True, to='ForumAccount.UserProfile'),
        ),
    ]
