# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-09 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumAccount', '0007_auto_20200408_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to='ForumAccount.UserProfile'),
        ),
    ]
