# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-09 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumAccount', '0008_friend_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='following',
            field=models.ManyToManyField(related_name='following', to='ForumAccount.UserProfile'),
        ),
    ]
