# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-23 20:02
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(null=True)),
                ('delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_file_to_user)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_file_to_user_cover)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_receiver', to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_sender', to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='friend',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_owner', to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='friend',
            name='following',
            field=models.ManyToManyField(related_name='following', to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='friend',
            name='friend_list',
            field=models.ManyToManyField(to='accounts.UserProfile'),
        ),
    ]
